name: Deploy Node EJS Site

on:
  push:
    branches:
      - Publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy project to server (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          source: "dist/, src/, views/, index.ts, public/, package.json"
          target: "/root/GitHubTemp"

      - name: Connect to server via SSH and finalize deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/webpage || exit 1
            # Suoritetaan apt-get päivitykset ilman käyttäjän väliintuloa
            sudo apt-get update -y
            sudo apt-get upgrade -y
            pm2 stop ecosystem.config.js --env production
            rsync -av /root/GitHubTemp/dist/ /root/webpage/
            rsync -av /root/GitHubTemp/src/ /root/webpage/
            rsync -av /root/GitHubTemp/views/ /root/webpage/
            rsync -av /root/GitHubTemp/public/ /root/webpage/
            cp -f /root/GitHubTemp/index.ts /root/webpage/
            cp -f /root/GitHubTemp/package.json /root/webpage/
            npm install
            npm audit fix
            pm2 start ecosystem.config.js --env production
